name: Prueba de tokens - v2

on:
  push:

jobs:
  comparar-tokens:
    runs-on: self-hosted

    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: cmd
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if "%DEV_TOKEN%"=="%LOCAL_DEV_TOKEN%" (
            echo Los tokens coinciden correctamente.
          ) else (
            echo Los tokens NO coinciden.
            exit /b 1
          )
